### ISSUE TITLE
listClients() return Catchable fatal error

### ISSUE THREAD

**Issue by kaliha** [bensnyde/php-solusvm-api#6]
Hello. I've try to recieve all clients with `$clients = $solus->listClients();` And recieve error: 
`Catchable fatal error: Argument 1 passed to Solus::execute() must be of the type array, string given, called in /home/ubuntu/workspace/solus.php on line 336 and defined in /home/ubuntu/workspace/solus.php on line 39`

**Comment by bensnyde** [comment]
Please download the latest version of the library.
